apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop
  labels:
    app: workshop
spec:
  selector:
    matchLabels:
      app: workshop
  replicas: 2
  revisionHistoryLimit: 7
  progressDeadlineSeconds: 800
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: workshop
      labels:
        app: workshop
        techstack: spring-boot
    spec:
#     Define volume with secrets value
      volumes:
        - name: workshop-secret
          secret:
            secretName: workshop-credentials-secret
      containers:
        - name: workshop
#         Grab properties from configmap
          envFrom:
            - configMapRef:
                name: workshop-configmap
#         Mount volume to container
          volumeMounts:
            - mountPath: /secret/app
              name: workshop-secret
          image: workshop:6
#         Declare ports (optional)
          ports:
            - containerPort: 8080
              name: main
#         Declare resource to avoid BestEffort mode
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
#         Configure liveness probe
          livenessProbe:
            httpGet:
              port: main
              path: /management/health
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          imagePullPolicy: IfNotPresent
      priorityClassName: high-priority # main service of a pod
      restartPolicy: Always
