apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-limit-range
spec:
  limits:
    - type: Container
#     Default request for container if not mentioned in container spec
      defaultRequest:
        cpu: 100m
        memory: 64Mi
#     Default limits for container if not mentioned in container spec
      default:
        cpu: 300m
        memory: 256Mi
      max:
        cpu: 600m
        memory: 512Mi