apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-quotas
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: 768Mi
    limits.cpu: 2000m
    limits.memory: 1Gi
    pods: "5"
    services: "1"
