apiVersion: v1
kind: Service
metadata:
  name: workshop-service
  labels:
    techstack: spring-boot
spec:
  selector:
    app: workshop
#  clusterIP: None
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
